version: '3.4'

services:

  envoygateway:
    build: Envoy/
    ports: 
      - 9901:9901
      #- 10000:10000
      - 10001:10001
    volumes: 
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./Envoy/https.crt:/etc/ssl/certs/https.crt
      - ./Envoy/key.pem:/etc/ssl/certs/key.pem

  inventorydb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  procurementdb:
    image: mongo

  materialinventory:
    image: ${DOCKER_REGISTRY-}materialinventory
    build:
      context: .
      dockerfile: MaterialInventory/Dockerfile

  procurement.api:
    image: ${DOCKER_REGISTRY-}procurement
    build:
      context: .
      dockerfile: Procurement/Procurement.API/Dockerfile
  
  reportaggregator:
    image: ${DOCKER_REGISTRY-}reportaggregator
    build:
      context: .
      dockerfile: Aggregator/Dockerfile

volumes:
  mongo_data:
